<?php
// Enable error reporting for local debugging
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

include "ai.php";

// ========== USER INPUT ==========
$from   = ucfirst(strtolower(trim($_POST['from'] ?? 'Delhi')));
$budget = (int)($_POST['budget'] ?? 40000);
$days   = (int)($_POST['days'] ?? 4);
$people = (int)($_POST['people'] ?? 2);
$region = $_POST['region'] ?? 'India';
$type   = $_POST['type'] ?? 'Family';

// ========== CALL AI ==========
$aiResults = aiSuggestDestinationsGemini($from, $budget, $days, $type, $region, $people);
$useAI = ($aiResults && is_array($aiResults) && count($aiResults) > 0);

// ========== FALLBACK DATA ==========
$citiesRegion = [
  'Delhi'=>'India','Agra'=>'India','Jaipur'=>'India','Goa'=>'India','Mumbai'=>'India',
  'Hyderabad'=>'India','Chennai'=>'India','Kochi'=>'India','Rishikesh'=>'India','Amritsar'=>'India'
];

$catalog = [
  'Delhi'=>3000,'Agra'=>2800,'Jaipur'=>3500,'Goa'=>4000,'Mumbai'=>4500,
  'Hyderabad'=>3200,'Chennai'=>3100,'Kochi'=>3000,'Rishikesh'=>2000,'Amritsar'=>2500
];

// Build fallback suggestions
$suggest = [];
foreach ($citiesRegion as $city => $reg) {
  if ($reg != $region) continue;
  $stay = $catalog[$city] ?? 3000;
  if ($stay * $days * $people < $budget * 0.7) {
    $suggest[] = ['city' => $city, 'stay' => $stay];
  }
}
usort($suggest, fn($a, $b) => $a['stay'] <=> $b['stay']);
$suggest = array_slice($suggest, 0, 8);
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Suggested Destinations</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
</head>
<body class="bg-light">
<nav class="navbar navbar-dark bg-primary mb-4">
  <div class="container">
    <a class="navbar-brand" href="index.php">Smart Trip Planner</a>
    <a href="explore.php" class="btn btn-light btn-sm">Back</a>
  </div>
</nav>

<div class="container">
  <h3>Suggested Destinations (<?=htmlspecialchars($region)?> · <?=htmlspecialchars($type)?>)</h3>

  <?php if ($useAI): ?>
    <h5 class="text-success mt-3">✨ AI Recommendations (from <?=htmlspecialchars($from)?>)</h5>
    <div class="row g-3 mt-2">
      <?php foreach ($aiResults as $s): ?>
        <div class="col-md-4">
          <div class="card shadow-sm">
            <div class="card-body">
              <h5><?=htmlspecialchars($s['city'] ?? 'Unknown City')?></h5>
              <p class="small text-muted"><?=htmlspecialchars($s['reason'] ?? 'Suggested destination')?></p>
              <?php if (!empty($s['estimatedCost'])): ?>
                <p>Est. Cost: ₹<?=number_format($s['estimatedCost'])?></p>
              <?php endif; ?>
              <form action="planner.php" method="POST">
                <input type="hidden" name="from" value="<?=htmlspecialchars($from)?>">
                <input type="hidden" name="to" value="<?=htmlspecialchars($s['city'] ?? '')?>">
                <input type="hidden" name="days" value="<?=$days?>">
                <input type="hidden" name="people" value="<?=$people?>">
                <input type="hidden" name="budget" value="<?=$budget?>">
                <input type="hidden" name="type" value="<?=htmlspecialchars($type)?>">
                <button class="btn btn-primary w-100">Plan Trip</button>
              </form>
            </div>
          </div>
        </div>
      <?php endforeach; ?>
    </div>

  <?php else: ?>
    <h5 class="text-secondary mt-3">📍 Fallback Suggestions</h5>
    <p class="text-muted">AI service unavailable or timed out — showing local destinations.</p>
    <div class="row g-3 mt-2">
      <?php foreach ($suggest as $s): ?>
        <div class="col-md-4">
          <div class="card shadow-sm">
            <div class="card-body">
              <h5><?=htmlspecialchars($s['city'])?></h5>
              <p class="small text-muted">Avg. ₹<?=number_format($s['stay'])?>/night</p>
              <form action="planner.php" method="POST">
                <input type="hidden" name="from" value="<?=htmlspecialchars($from)?>">
                <input type="hidden" name="to" value="<?=htmlspecialchars($s['city'])?>">
                <input type="hidden" name="days" value="<?=$days?>">
                <input type="hidden" name="people" value="<?=$people?>">
                <input type="hidden" name="budget" value="<?=$budget?>">
                <input type="hidden" name="type" value="<?=htmlspecialchars($type)?>">
                <button class="btn btn-primary w-100">Plan Trip</button>
              </form>
            </div>
          </div>
        </div>
      <?php endforeach; ?>
    </div>
  <?php endif; ?>

  <hr>
  <div class="mt-3 text-muted">
    <small>
      <?php if ($useAI): ?>
        ✅ AI Mode Active — Results generated by GPT-5 using your travel preferences.
      <?php else: ?>
        ⚠️ AI Mode Disabled — Using fallback suggestions (check <code>logs/ai_error.txt</code> for details).
      <?php endif; ?>
    </small>
  </div>
</div>
</body>
</html>
